--THIS FILE CONTAINS THE DESCRIPTION OF THE DATA STRUCTURE OF THE
--IMPORT DATA FOR THE CLASSICAL SCE DOWNLOAD FROM R/3
CREATE TABLE T100
(
    SPRSL       CHAR(2)               NOT NULL,
    ARBGB       CHAR(20)              NOT NULL,
    MSGNR       CHAR(3)               NOT NULL,
    DESCRIPT    NCHAR(73)             NOT NULL,
    CONSTRAINT PK_T100 PRIMARY KEY (SPRSL, ARBGB, MSGNR)
)
GO

CREATE TABLE SCET002
(
    LANGUAGEID  CHAR(1)               NOT NULL,
    SPRSL       CHAR(2)               NOT NULL,
    CONSTRAINT PK_SCET002 PRIMARY KEY (LANGUAGEID)
)
GO

CREATE TABLE SCEKB
(
    KBID        INT                   NOT NULL,
    KBOBJNAME   CHAR(30)              NOT NULL,
    VERSION     CHAR(30)              NOT NULL,
    BUILD       SMALLINT              NOT NULL,
    FROMDATE    DATE               NOT NULL,
    STATUS      SMALLINT              NOT NULL,
    CREATOR     CHAR(12)              NOT NULL,
    CREADATE    DATE               NOT NULL,
    CHANGER     CHAR(12)              NULL    ,
    CHANGEDATE  DATE               NULL    ,
    LANG_DOWN   CHAR(1)               NULL    ,
    ORGID       CHAR(4)               NOT NULL,
    BOM_APPL    CHAR(4)               NOT NULL,
    KLART_DOWN  CHAR(3)               NULL    ,
    CLASSICDEP  CHAR(1)               NOT NULL,
    ACTIONFLAG  CHAR(1)               NOT NULL,
    KBSCHEMA    SMALLINT              NULL,
    CONSTRAINT PK_SCEKB PRIMARY KEY (KBID)
)
GO

CREATE TABLE CFGHEADER
(
    CFGID       INT                   NOT NULL,
    KBNAME      CHAR(18)              NOT NULL,
    VERSION     CHAR(30)              NOT NULL,
    BUILD       SMALLINT              NOT NULL,
    R3ID        INT                   NOT NULL,
    SAVEDATE    CHAR(8)               NOT NULL,
    SAVETIME    CHAR(6)               NOT NULL,
    STATUS      SMALLINT               NOT NULL,
    CFGUSER     INT                   NOT NULL,
    ROOT        INT                   NOT NULL,
    PROFNAME    CHAR(30)              NOT NULL,
    CONSISTENT  CHAR(1)               NOT NULL,
    COMPLETE    CHAR(1)               NOT NULL,
    SOUND       SMALLINT               NOT NULL,
    FORMAT      SMALLINT               NOT NULL,
    DOC         CHAR(60)              NULL    ,
    LANGUAGEID  CHAR(1)               NULL    ,
    CONSTRAINT PK_CFGHEADER PRIMARY KEY (CFGID)
)
GO

CREATE TABLE SCECHARAC
(
    KBID        INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    CHARNAME    CHAR(30)              NOT NULL,
    DATATYPE    INT                   NOT NULL,
    CHARKIND    SMALLINT               NOT NULL,
    ADDITVALUE  CHAR(1)               NULL    ,
    CONSTRAINT PK_SCECHARAC PRIMARY KEY (KBID, CHARID)
)
GO

CREATE TABLE SCEDECOMP
(
    KBID        INT                   NOT NULL,
    DECOMPID    CHAR(8)               NOT NULL,
    NONMODELED  CHAR(1)               NULL    ,
    CONSTRAINT PK_SCEDECOMP PRIMARY KEY (KBID, DECOMPID),
    CONSTRAINT FK_DECOMP_KB FOREIGN KEY  (KBID)
       REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCEOCLASS
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    OBJNAME     CHAR(50)              NOT NULL,
    OBJTYPE     SMALLINT               NOT NULL,
    CLASSTYPE   CHAR(3)               NULL    ,
    CONSTRAINT PK_SCEOCLASS PRIMARY KEY (KBID, OBJID),
    CONSTRAINT FK_OCLASS_KB FOREIGN KEY  (KBID) REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCECNT
(
    KBID        INT                   NOT NULL,
    CONTID      INT                   NOT NULL,
    CONTNAME    CHAR(30)              NULL    ,
    CONTTYPE    SMALLINT               NULL    ,
    CONSTRAINT PK_SCECNT PRIMARY KEY (KBID, CONTID),
    CONSTRAINT FK_CNT_KB FOREIGN KEY  (KBID) REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCEDEP
(
    KBID        INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    DEPNAME     CHAR(30)              NOT NULL,
    DEPTYPE     SMALLINT               NOT NULL,
    NETID       INT                   NULL    ,
    CONSTRAINT PK_SCEDEP PRIMARY KEY (KBID, DEPID),
    CONSTRAINT FK_DEP_KB FOREIGN KEY  (KBID) REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCEVALSYM
(
    KBID        INT                   NOT NULL,
    SYMBOLID    INT                   NOT NULL,
    DATATYPE    SMALLINT               NULL    ,
    CHARVALUE   CHAR(30)              NULL    ,
    CONSTRAINT PK_SCEVALSYM PRIMARY KEY (KBID, SYMBOLID),
    CONSTRAINT FK_VALSYM_KB FOREIGN KEY  (KBID) REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCENUM
(
    KBID        INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    UNIT        CHAR(3)               NULL    ,
    LENGTH      SMALLINT               NULL    ,
    SCALE       SMALLINT               NULL    ,
    TEMPLATE    CHAR(30)              NULL    ,
    CONSTRAINT PK_SCENUM PRIMARY KEY (KBID, CHARID),
    CONSTRAINT FK_NUM_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCESTRING
(
    KBID        INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    LENGTH      SMALLINT               NOT NULL,
    TEMPLATE    CHAR(30)              NULL    ,
    CASEFLAG    CHAR(1)               NULL    ,
    CONSTRAINT PK_SCESTRING PRIMARY KEY (KBID, CHARID),
    CONSTRAINT FK_STRING_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCEHASCHA
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    REQUIRED    CHAR(1)               NULL    ,
    CLASSIFREL  CHAR(1)               NULL    ,
    CONSTRAINT PK_SCEHASCHA PRIMARY KEY (KBID, OBJID, CHARID),
    CONSTRAINT FK_HASCHA_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_HASCHA_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCEMAT
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    MATTYPE     CHAR(4)               NOT NULL,
    BASEUNIT    CHAR(3)               NULL    ,
    CONSTRAINT PK_SCEMAT PRIMARY KEY (KBID, OBJID),
    CONSTRAINT FK_MAT_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID)
)
GO

CREATE TABLE SCEHASPRT
(
    KBID        INT                   NOT NULL,
    DECOMPID    CHAR(8)               NOT NULL,
    POSID       INT                   NOT NULL,
    OBJID       INT                   NULL    ,
    POSMIN      SMALLINT              NOT NULL,
    POSMAX      SMALLINT              NOT NULL,
    ALTGROUPID  INT                   NULL    ,
    CONGROUPID  INT                   NULL    ,
    POSNR       CHAR(4)               NOT NULL,
    SALESRELEV  CHAR(1)               NULL    ,
    CONSTRAINT PK_SCEHASPRT PRIMARY KEY (KBID, DECOMPID, POSID),
    CONSTRAINT FK_HASPRT_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_HASPRT_DECOMP FOREIGN KEY  (KBID, DECOMPID) REFERENCES SCEDECOMP (KBID, DECOMPID)
)
GO

CREATE TABLE SCEPROF
(
    KBID        INT                   NOT NULL,
    PROFNAME    CHAR(30)              NOT NULL,
    OBJID       INT                   NULL    ,
    UINAME      CHAR(30)              NULL    ,
    CONSTRAINT PK_SCEPROF PRIMARY KEY (KBID, PROFNAME),
    CONSTRAINT FK_PROF_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_PROF_KB FOREIGN KEY  (KBID) REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCEDEPDNN
(
    KBID        INT                   NOT NULL,
    NETID       INT                   NOT NULL,
    DNNID       INT                   NOT NULL,
    DNNTYPE     SMALLINT               NULL    ,
    L_PREDN     INT                   NULL    ,
    R_PREDN     INT                   NULL    ,
    CODEIDX     INT                   NULL    ,
    CONSTRAINT PK_SCEDEPDNN PRIMARY KEY (KBID, NETID, DNNID),
    CONSTRAINT FK_DEPDNN_DEP FOREIGN KEY  (KBID, NETID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCESTRDOM
(
    KBID        INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    SYMBOLID    INT                   NOT NULL,
    POSNR       SMALLINT              NULL    ,
    CVSYMID     INT                   NULL,
    CONSTRAINT PK_SCESTRDOM PRIMARY KEY (KBID, CHARID, SYMBOLID),
    CONSTRAINT FK_STRDOM_VALSYM FOREIGN KEY  (KBID, SYMBOLID) REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_STRDOM_STRING FOREIGN KEY  (KBID, CHARID) REFERENCES SCESTRING (KBID, CHARID)
)
GO

CREATE TABLE SCECHAPOS
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    POSNR       SMALLINT              NOT NULL,
    CONSTRAINT PK_SCECHAPOS PRIMARY KEY (KBID, OBJID, CHARID),
    CONSTRAINT FK_CHAPOS_OCLASS FOREIGN KEY  (KBID, OBJID)  REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_CHAPOS_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCECHATX
(
    KBID        INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    LANGUAGEID  CHAR(1)               NOT NULL,
    DESCRIPT    NCHAR(30)              NOT NULL,
    CONSTRAINT PK_SCECHATX PRIMARY KEY (KBID, CHARID, LANGUAGEID),
    CONSTRAINT FK_CHATX_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCECHAVIS
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    INVISIBLE   CHAR(1)               NOT NULL,
    CONSTRAINT PK_SCECHAVIS PRIMARY KEY (KBID, OBJID, CHARID),
    CONSTRAINT FK_CHAVIS_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_CHAVIS_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCECLPREC
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    POSID       INT                   NOT NULL,
    CONSTRAINT PK_SCECLPREC PRIMARY KEY (KBID, OBJID),
    CONSTRAINT FK_CLPREC_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID)
)
GO

CREATE TABLE SCECLNDOM
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    SYMBOLFROM  INT                   NOT NULL,
    VALUECODE   SMALLINT               NOT NULL,
    SYMBOLTO    INT                   NULL    ,
    CONSTRAINT PK_SCECLNDOM PRIMARY KEY (KBID, OBJID, CHARID, SYMBOLFROM, VALUECODE),
    CONSTRAINT FK_CLNDOM_VALSYM_T FOREIGN KEY  (KBID, SYMBOLTO) REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_CLNDOM_VALSYM_F FOREIGN KEY  (KBID, SYMBOLFROM) REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_CLNDOM_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_CLNDOM_NUM FOREIGN KEY  (KBID, CHARID) REFERENCES SCENUM (KBID, CHARID) 
)
GO

CREATE TABLE SCECLVAL
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    SYMBOLID    INT                   NOT NULL,
    VALUETYPE   SMALLINT               NULL    ,
    CONSTRAINT PK_SCECLVAL PRIMARY KEY (KBID, OBJID, CHARID, SYMBOLID),
    CONSTRAINT FK_CLVAL_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_CLVAL_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID),
    CONSTRAINT FK_CLVAL_VALSYM FOREIGN KEY  (KBID, SYMBOLID) REFERENCES SCEVALSYM (KBID, SYMBOLID)
)
GO

CREATE TABLE SCECLSDOM
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    SYMBOLID    INT                   NOT NULL,
    CONSTRAINT PK_SCECLSDOM PRIMARY KEY (KBID, OBJID, CHARID, SYMBOLID),
    CONSTRAINT FK_CLSDOM_VALSYM FOREIGN KEY  (KBID, SYMBOLID) REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_CLSDOM_STRING FOREIGN KEY  (KBID, CHARID) REFERENCES SCESTRING (KBID, CHARID),
    CONSTRAINT FK_CLSDOM_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID)
)
GO

CREATE TABLE SCECLVTX
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    SYMBOLID    INT                   NOT NULL,
    LANGUAGEID  CHAR(1)               NOT NULL,
    DESCRIPT    NCHAR(30)             NOT NULL,
    CONSTRAINT PK_SCECLVTX PRIMARY KEY (KBID, OBJID, CHARID, SYMBOLID, LANGUAGEID),
    CONSTRAINT FK_CLVTX_VALSYM FOREIGN KEY  (KBID, SYMBOLID) REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_CLVTX_STRING FOREIGN KEY  (KBID, CHARID) REFERENCES SCESTRING (KBID, CHARID),
    CONSTRAINT FK_CLVTX_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID)
)
GO

CREATE TABLE SCEDEPCOM
(
    KBID        INT                   NOT NULL,
    NETID       INT                   NOT NULL,
    CODEIDX     INT                   NOT NULL,
    TERMID      INT                   NOT NULL,
    TYPE        SMALLINT              NOT NULL,
    OPERATOR    INT                   NOT NULL,
    ARG1        SMALLINT              NOT NULL,
    ARG2        SMALLINT              NOT NULL,
    CONSTRAINT PK_SCEDEPCOM PRIMARY KEY (KBID, NETID, CODEIDX, TERMID),
    CONSTRAINT FK_DEPCO_DEP FOREIGN KEY  (KBID, NETID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCEDEPDOC
(
    KBID        INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    LINEID      SMALLINT              NOT NULL,
    LANGUAGEID  CHAR(1)               NOT NULL,
    TEXTFORM    CHAR(2)               NULL,
    TEXTLINE    NCHAR(132)            NOT NULL,
    CONSTRAINT PK_SCEDEPDOC PRIMARY KEY (KBID, DEPID, LINEID, LANGUAGEID),
    CONSTRAINT FK_DEPDOC_DEP FOREIGN KEY  (KBID, DEPID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCEDEPSRC
(
    KBID        INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    LINEID      SMALLINT              NOT NULL,
    LINE        CHAR(72)              NOT NULL,
    CONSTRAINT PK_SCEDEPSRC PRIMARY KEY (KBID, DEPID, LINEID),
    CONSTRAINT FK_DEPSRC_DEP FOREIGN KEY  (KBID, DEPID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCEDEPTX
(
    KBID        INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    LANGUAGEID  CHAR(1)               NOT NULL,
    DESCRIPT    NCHAR(30)             NOT NULL,
    CONSTRAINT PK_SCEDEPTX PRIMARY KEY (KBID, DEPID, LANGUAGEID),
    CONSTRAINT FK_DEPTX_DEP FOREIGN KEY  (KBID, DEPID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCENUMDOM
(
    KBID        INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    SYMBOLFROM  INT                   NOT NULL,
    VALUECODE   SMALLINT              NOT NULL,
    SYMBOLTO    INT                   NULL    ,
    POSNR       SMALLINT              NULL    ,
    CVNUMID     INT                   NULL,
    CONSTRAINT PK_SCENUMDOM PRIMARY KEY (KBID, CHARID, SYMBOLFROM, VALUECODE),
    CONSTRAINT FK_NUMDOM_VALSYM_T FOREIGN KEY  (KBID, SYMBOLTO) REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_NUMDOM_VALSYM_F FOREIGN KEY  (KBID, SYMBOLFROM) REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_NUMDOM_NUM FOREIGN KEY  (KBID, CHARID) REFERENCES SCENUM (KBID, CHARID)
)
GO

CREATE TABLE SCEINVIEW
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    VIEWID      CHAR(1)               NOT NULL,
    CONSTRAINT PK_SCEINVIEW PRIMARY KEY (KBID, OBJID, CHARID, VIEWID),
    CONSTRAINT FK_INVIEW_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_INVIEW_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCEOCLTX
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    LANGUAGEID  CHAR(1)               NOT NULL,
    DESCRIPT    NCHAR(40)             NOT NULL,
    CONSTRAINT PK_SCEOCLTX PRIMARY KEY (KBID, OBJID, LANGUAGEID),
    CONSTRAINT FK_OCLTX_OCLASS FOREIGN KEY  (KBID, OBJID) REFERENCES SCEOCLASS (KBID, OBJID)
)
GO

CREATE TABLE SCESUPER
(
    KBID        INT                   NOT NULL,
    SUBOBJID    INT                   NOT NULL,
    SUPOBJID    INT                   NOT NULL,
    POSNR       SMALLINT              NOT NULL,
    CONSTRAINT PK_SCESUPER PRIMARY KEY (KBID, SUBOBJID, SUPOBJID),
    CONSTRAINT FK_SUPER_OCLASS_P FOREIGN KEY  (KBID, SUPOBJID) REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_SUPER_OCLASS_B FOREIGN KEY  (KBID, SUBOBJID) REFERENCES SCEOCLASS (KBID, OBJID)
)
GO

CREATE TABLE SCEVALTX
(
    KBID        INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    SYMBOLID    INT                   NOT NULL,
    LANGUAGEID  CHAR(1)               NOT NULL,
    DESCRIPT    NCHAR(30)             NOT NULL,
    CONSTRAINT PK_SCEVALTX PRIMARY KEY (KBID, CHARID, SYMBOLID, LANGUAGEID),
    CONSTRAINT FK_VALTX_STRDOM FOREIGN KEY  (KBID, CHARID, SYMBOLID) REFERENCES SCESTRDOM (KBID, CHARID, SYMBOLID)
)
GO

CREATE TABLE TRCLEVELS
(
    KBID        INT                   NOT NULL,
    UNAME       CHAR(12)              NOT NULL,
    INLEVEL     SMALLINT               NOT NULL,
    OUTLEVEL    SMALLINT               NULL    ,
    CONSTRAINT PK_TRCLEVELS PRIMARY KEY (KBID, UNAME),
    CONSTRAINT FK_TRCLEVEL_KB FOREIGN KEY  (KBID)  REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE TRCINMOD
(
    KBID        INT                   NOT NULL,
    UNAME       CHAR(12)              NOT NULL,
    MODULE      CHAR(10)              NOT NULL,
    CONSTRAINT PK_TRCINMOD PRIMARY KEY (KBID, UNAME, MODULE),
    CONSTRAINT FK_TRCINMOD_KB FOREIGN KEY  (KBID) REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE TRCMODOBJ
(
    KBID        INT                   NOT NULL,
    UNAME       CHAR(12)              NOT NULL,
    MODULE      CHAR(10)              NOT NULL,
    OBJECT      CHAR(50)              NOT NULL,
    OBJECTTYPE  CHAR(50)              NOT NULL,
    CONSTRAINT PK_TRCMODOBJ PRIMARY KEY (KBID, UNAME, MODULE, OBJECT, OBJECTTYPE),
    CONSTRAINT FK_TRCMODOBJ_KB FOREIGN KEY  (KBID) REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCEHASDEC
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    DECOMPID    CHAR(8)               NOT NULL,
    CONSTRAINT PK_SCEHASDEC PRIMARY KEY (KBID, OBJID, DECOMPID),
    CONSTRAINT FK_HASDEC_OCLASS FOREIGN KEY  (KBID, OBJID)  REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_HASDEC_DECOMP FOREIGN KEY  (KBID, DECOMPID) REFERENCES SCEDECOMP (KBID, DECOMPID)
)
GO

CREATE TABLE CFGTO
(
    CFGID       INT                   NOT NULL,
    TOFACTID    INT                   NOT NULL,
    OBJNAME     CHAR(50)              NOT NULL,
    OBJTYPE     SMALLINT              NOT NULL,
    CLASSTYPE   CHAR(3)               NOT NULL,
    INSTID      INT                   NOT NULL,
    CURRENTP    CHAR(1)               NOT NULL,
    OBJTXT      CHAR(40)              NOT NULL,
    OWNER       CHAR(1)               NOT NULL,
    CONSTRAINT PK_CFGTO PRIMARY KEY (CFGID, TOFACTID, OBJNAME, OBJTYPE, CLASSTYPE),
    CONSTRAINT FK_CFGTO_CFGHEADER FOREIGN KEY (CFGID) REFERENCES CFGHEADER (CFGID)
)
GO

CREATE TABLE CFGHP
(
    CFGID       INT                   NOT NULL,
    HPFACTID    INT                   NOT NULL,
    PARENTID    INT                   NOT NULL,
    CHILDID     INT                   NOT NULL,
    POSID       INT                   NULL    ,
    POSNR       CHAR(4)               NOT NULL,
    OBJNAME     CHAR(50)              NOT NULL,
    OBJTXT      CHAR(40)              NOT NULL,
    OBJTYPE     SMALLINT              NOT NULL,
    CLASSTYPE   CHAR(3)               NOT NULL,
    OWNER       CHAR(1)               NOT NULL,
    CONSTRAINT PK_CFGHP PRIMARY KEY (CFGID, HPFACTID),
    CONSTRAINT FK_CFGHP_CFGHEADER FOREIGN KEY  (CFGID) REFERENCES CFGHEADER (CFGID)
)
GO

CREATE TABLE CFGHV
(
    CFGID       INT                   NOT NULL,
    HVFACTID    INT                   NOT NULL,
    INSTID      INT                   NOT NULL,
    CHARNAME    CHAR(30)              NOT NULL,
    CHARTXT     CHAR(30)              NOT NULL,
    DATATYPE    INT                   NOT NULL,
    CHARKIND    SMALLINT              NOT NULL,
    CHARVALUE   CHAR(30)              NULL    ,
    VALUETXT    CHAR(30)              NULL    ,
    VALUEPOS    SMALLINT              NOT NULL,
    CHARACPOS   SMALLINT              NOT NULL,
    OWNER       CHAR(1)               NOT NULL,
    CONSTRAINT PK_CFGHV PRIMARY KEY (CFGID, HVFACTID),
    CONSTRAINT FK_CFGHV_CFGHEADER FOREIGN KEY  (CFGID)
       REFERENCES CFGHEADER (CFGID)
)
GO

CREATE TABLE CFGHF
(
    CFGID       INT                   NOT NULL,
    HFFACTID    INT                   NOT NULL,
    CHARVALUE   CHAR(30)              NOT NULL,
    VALUECODE   SMALLINT              NOT NULL,
    INSTID      INT                   NOT NULL,
    CHARNAME    CHAR(30)              NULL    ,
    CHARTXT     CHAR(30)              NULL    ,
    DATATYPE    INT                   NULL    ,
    CHARKIND    SMALLINT              NULL    ,
    VALUEPOS    SMALLINT              NULL    ,
    FACET       SMALLINT               NOT NULL,
    VALUETXT    CHAR(30)              NULL    ,
    NUMVALTO    CHAR(30)              NULL    ,
    OWNER       CHAR(1)               NOT NULL,
    POSID       INT                   NULL    ,
    POSNR       CHAR(4)               NULL    ,
    OBJNAME     CHAR(50)              NULL    ,
    OBJTXT      CHAR(40)              NULL    ,
    OBJTYPE     SMALLINT               NULL    ,
    CLASSTYPE   CHAR(3)               NULL    ,
    CONSTRAINT PK_CFGHF PRIMARY KEY (CFGID, HFFACTID, CHARVALUE, VALUECODE),
    CONSTRAINT FK_CFGHF_CFGHEADER FOREIGN KEY  (CFGID)
       REFERENCES CFGHEADER (CFGID)
)
GO

CREATE TABLE CFGJUST
(
    CFGID       INT                   NOT NULL,
    JUSTID      INT                   NOT NULL,
    SUPPORT     INT                   NOT NULL,
    SUPSTYPE    SMALLINT              NOT NULL,
    SUPEDFACT   INT                   NOT NULL,
    SUPEDTYPE   SMALLINT              NOT NULL,
    KNTYPE      CHAR(1)               NULL    ,
    SEGMENT     INT                   NULL    ,
    AUTHOR      INT                   NULL    ,
    CONSTRAINT PK_CFGJUST PRIMARY KEY (CFGID, JUSTID, SUPPORT),
    CONSTRAINT FK_CFGJUST_CFGHDR FOREIGN KEY  (CFGID)
       REFERENCES CFGHEADER (CFGID)
)
GO

CREATE TABLE SCETABFUN
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    ALTNR       SMALLINT              NOT NULL,
    CHARID      INT                   NOT NULL,
    CONSTRAINT PK_SCETABFUN PRIMARY KEY (KBID, OBJID, ALTNR, CHARID),
    CONSTRAINT FK_TABFUN_OCLASS FOREIGN KEY  (KBID, OBJID)
       REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_TABFU_CHARAC FOREIGN KEY  (KBID, CHARID)
       REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCEDEPSPN
(
    KBID        INT                   NOT NULL,
    NETID       INT                   NOT NULL,
    SPNID       INT                   NOT NULL,
    CLASS1ID    INT                   NULL    ,
    CLASS2ID    INT                   NULL    ,
    SP          INT                   NULL    ,
    SPTYPE      SMALLINT              NULL    ,
    CONSTRAINT PK_SCEDEPSPN PRIMARY KEY (KBID, NETID, SPNID),
    CONSTRAINT FK_DEPSPN_OCLASS FOREIGN KEY  (KBID, CLASS1ID)
       REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_DEPSPN_DEP FOREIGN KEY  (KBID, NETID)
       REFERENCES SCEDEP (KBID, DEPID)   
)
GO

CREATE TABLE SCEDEPPAT
(
    KBID        INT                   NOT NULL,
    NETID       INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    PT_VARICNT  INT                   NOT NULL,
    DNNID       INT                   NULL    ,
    CODEIDX     INT                   NULL    ,
    PRIO        SMALLINT              NULL    ,
    CONSTRAINT PK_SCEDEPPAT PRIMARY KEY (KBID, NETID, DEPID, PT_VARICNT),
    CONSTRAINT FK_DEPPAT_DEPDNN FOREIGN KEY  (KBID, NETID, DNNID)
       REFERENCES SCEDEPDNN (KBID, NETID, DNNID),
    CONSTRAINT FK_DEPPAT_DEP FOREIGN KEY  (KBID, DEPID)
       REFERENCES SCEDEP (KBID, DEPID)   
)
GO

CREATE TABLE SCECNTTX
(
    KBID        INT                   NOT NULL,
    CONTID      INT                   NOT NULL,
    LANGUAGEID  CHAR(1)               NOT NULL,
    DESCRIPT    NCHAR(30)             NULL    ,
    CONSTRAINT PK_SCECNTTX PRIMARY KEY (KBID, CONTID, LANGUAGEID),
    CONSTRAINT FK_CNTTX_CNT FOREIGN KEY  (KBID, CONTID)
       REFERENCES SCECNT (KBID, CONTID)
)
GO

CREATE TABLE SCECNTDEP
(
    KBID        INT                   NOT NULL,
    CONTID      INT                   NOT NULL,
    NETID       INT                   NOT NULL,
    POSNR       SMALLINT              NULL    ,
    CONSTRAINT PK_SCECNTDEP PRIMARY KEY (KBID, CONTID, NETID),
    CONSTRAINT FK_CNTDEP_DEP FOREIGN KEY  (KBID, NETID)
       REFERENCES SCEDEP (KBID, DEPID),
    CONSTRAINT FK_CNTDEP_CNT FOREIGN KEY  (KBID, CONTID)
       REFERENCES SCECNT (KBID, CONTID)   
)
GO

CREATE TABLE SCEKBTX
(
    KBID        INT                   NOT NULL,
    LANGUAGEID  CHAR(10)              NOT NULL,
    DESCRIPT    NCHAR(30)             NULL    ,
    CONSTRAINT PK_SCEKBTX PRIMARY KEY (KBID, LANGUAGEID),
    CONSTRAINT FK_KBTX_KB FOREIGN KEY  (KBID)
       REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCEPROFTX
(
    KBID        INT                   NOT NULL,
    PROFNAME    CHAR(30)              NOT NULL,
    LANGUAGEID  CHAR(1)               NOT NULL,
    DESCRIPT    NCHAR(30)              NULL    ,
    CONSTRAINT PK_SCEPROFTX PRIMARY KEY (KBID, PROFNAME, LANGUAGEID),
    CONSTRAINT FK_PROFTX_PROF FOREIGN KEY  (KBID, PROFNAME)
       REFERENCES SCEPROF (KBID, PROFNAME)
)
GO

CREATE TABLE SCEDEPVAR
(
    KBID        INT                   NOT NULL,
    NETID       INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    SYMBOLID    INT                   NOT NULL,
    OBJID       INT                   NULL    ,
    CHARID      INT                   NULL    ,
    SPTYPE      SMALLINT              NULL    ,
    IOFLAG      CHAR(2)               NULL    ,
    CONSTRAINT PK_SCEDEPVAR PRIMARY KEY (KBID, NETID, DEPID, SYMBOLID),
    CONSTRAINT FK_DEPVAR_DEP_NET FOREIGN KEY  (KBID, NETID)
       REFERENCES SCEDEP (KBID, DEPID),
    CONSTRAINT FK_DEPVAR_VALSYM FOREIGN KEY  (KBID, SYMBOLID)
       REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_DEPVAR_DEP_DEP FOREIGN KEY  (KBID, DEPID)
       REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCEKMTDEP
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    POSNR       SMALLINT              NULL    ,
    DEPPOS      SMALLINT              NULL    ,
    PROC_EVENT  SMALLINT              NULL    ,
    CONSTRAINT PK_SCEKMTDEP PRIMARY KEY (KBID, OBJID, DEPID),
    CONSTRAINT FK_KMTDEP_MAT FOREIGN KEY  (KBID, OBJID) REFERENCES SCEMAT (KBID, OBJID),
    CONSTRAINT FK_KMTDEP_DEP FOREIGN KEY  (KBID, DEPID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCEPRTDEP
(
    KBID        INT                   NOT NULL,
    DECOMPID    CHAR(8)               NOT NULL,
    POSID       INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    POSNR       SMALLINT              NULL    ,
    DEPPOS      SMALLINT              NULL    ,
    PROC_EVENT  SMALLINT              NULL    ,
    CONSTRAINT PK_SCEPRTDEP PRIMARY KEY (KBID, DECOMPID, POSID, DEPID),
    CONSTRAINT FK_PRTDEP_HASPRT FOREIGN KEY  (KBID, DECOMPID, POSID) REFERENCES SCEHASPRT (KBID, DECOMPID, POSID),
    CONSTRAINT FK_PRTDEP_DEP FOREIGN KEY  (KBID, DEPID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCECHADEP
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    CONSTRAINT PK_SCECHADEP PRIMARY KEY (KBID, OBJID, CHARID, DEPID),
    CONSTRAINT FK_CHADEP_HASCHA FOREIGN KEY  (KBID, OBJID, CHARID) REFERENCES SCEHASCHA (KBID, OBJID, CHARID),
    CONSTRAINT FK_CHADEP_DEP FOREIGN KEY  (KBID, DEPID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCEVALDEP
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    SYMBOLID    INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    CONSTRAINT PK_SCEVALDEP PRIMARY KEY (KBID, OBJID, CHARID, SYMBOLID, DEPID),
    CONSTRAINT FK_VALDEP_VALSYM FOREIGN KEY  (KBID, SYMBOLID) REFERENCES SCEVALSYM (KBID, SYMBOLID),
    CONSTRAINT FK_VALDEP_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID),
    CONSTRAINT FK_VALDEP_OCLASS FOREIGN KEY  (KBID, OBJID)  REFERENCES SCEOCLASS (KBID, OBJID),
    CONSTRAINT FK_VALDEP_DEP FOREIGN KEY  (KBID, DEPID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCECHAINP
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    NO_ENTRY    CHAR(1)               NULL    ,
    CONSTRAINT PK_SCECHAINP PRIMARY KEY (KBID, OBJID, CHARID),
    CONSTRAINT FK_CHAINP_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID),
    CONSTRAINT FK_CHAINP_OCLASS FOREIGN KEY  (KBID, OBJID)  REFERENCES SCEOCLASS (KBID, OBJID)
)
GO

CREATE TABLE SCECLACOM
(
    KBID        INT                   NOT NULL,
    DEPID       INT                   NOT NULL,
    TERMID      INT                   NOT NULL,
    TYPE        SMALLINT              NOT NULL,
    OPERATOR    INT                   NOT NULL,
    ARG1        SMALLINT              NOT NULL,
    ARG2        SMALLINT              NOT NULL,
    CONSTRAINT PK_SCECLACOM PRIMARY KEY (KBID, DEPID, TERMID),
    CONSTRAINT FK_CLACOM_DEP FOREIGN KEY  (KBID, DEPID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCEDEPBLOB
(
    KBID        INT                   NOT NULL,
    NETID       INT                   NOT NULL,
    COMPILATE   LONGVARBINARY         NOT NULL,
    CONSTRAINT PK_SCEDEPBLOB PRIMARY KEY (KBID, NETID),
    CONSTRAINT FK_DEPBLOB_DEP FOREIGN KEY  (KBID, NETID) REFERENCES SCEDEP (KBID, DEPID)
)
GO

CREATE TABLE SCECHAREF
(
    KBID        INT                   NOT NULL,
    CHARID      INT                   NOT NULL,
    TABLENAME   CHAR(30)              NOT NULL,
    FIELDNAME   CHAR(30)              NOT NULL,
    CONSTRAINT PK_SCECHAREF PRIMARY KEY (KBID, CHARID, TABLENAME, FIELDNAME),
    CONSTRAINT FK_CHAREF_CHARAC FOREIGN KEY  (KBID, CHARID) REFERENCES SCECHARAC (KBID, CHARID)
)
GO

CREATE TABLE SCECONFPR
(
    KBID        INT                   NOT NULL,
    OBJID       INT                   NOT NULL,
    CONFPRNAME  CHAR(30)              NOT NULL,
    BOM_APPL    CHAR(4)               NULL    ,
    SCENARIO    SMALLINT              NOT NULL,
    DECOMP_MAN  CHAR(1)               NOT NULL,
    VALUE_MAN   CHAR(1)               NOT NULL,
    DSINT       INT                   NULL,
    CONSTRAINT PK_SCECONFPR PRIMARY KEY (KBID, OBJID),
    CONSTRAINT FK_CONFPR_MAT FOREIGN KEY  (KBID, OBJID) REFERENCES SCEMAT (KBID, OBJID)
)
GO

CREATE TABLE SCECNTBLOB
(
    KBID        INT                   NOT NULL,
    CONTID      INT                   NOT NULL,
    COMPILATE   LONGVARBINARY         NOT NULL,
    CONSTRAINT PK_SCECNTBLOB PRIMARY KEY (KBID, CONTID),
    CONSTRAINT FK_CNTBLOB_CNT FOREIGN KEY  (KBID, CONTID) REFERENCES SCECNT (KBID, CONTID)
)
GO

CREATE TABLE SCECLABLOB
(
    KBID        INT                   NOT NULL,
    COMPILATE   LONGVARBINARY         NOT NULL,
    CONSTRAINT PK_SCECLABLOB PRIMARY KEY (KBID)
)
GO

CREATE TABLE SCEVACOND (
     KBID    INT     NOT NULL,
     OBJID   INT     NOT NULL,
     CHARID  INT     NOT NULL,
     SYMBOLID INT    NOT NULL,
     VARCOND CHAR(26) NOT NULL,
     CONSTRAINT PK_SCEVACOND PRIMARY KEY (KBID,OBJID,CHARID,SYMBOLID),
     CONSTRAINT FK_VACOND_VALSYM FOREIGN KEY(KBID,SYMBOLID) REFERENCES SCEVALSYM(KBID,SYMBOLID),
     CONSTRAINT FK_VACOND_OCLASS FOREIGN KEY(KBID,OBJID) REFERENCES SCEOCLASS(KBID,OBJID),
     CONSTRAINT FK_VACOND_CHARAC FOREIGN KEY(KBID,CHARID) REFERENCES SCECHARAC(KBID,CHARID)
)
GO

CREATE TABLE SCECUHD (
     KBID    INT        NOT NULL,
     DESIGN  CHAR(18)   NOT NULL,
     DSINT   INT        NOT NULL,
     CONSTRAINT PK_SCEUHD PRIMARY KEY (KBID,DSINT),
     CONSTRAINT FK_CUHD_KB FOREIGN KEY(KBID) REFERENCES SCEKB(KBID)
)
GO

CREATE TABLE SCECUSD (
     KBID   INT     NOT NULL,
     DSINT  INT     NOT NULL,
     GRINT  INT     NOT NULL,
     COUNTER   SMALLINT    NOT NULL,
     COMP   CHAR(1)     NOT NULL,
     S_SALES    CHAR(1)     NOT NULL,
     S_ENGINEERING CHAR(1)  NOT NULL,
     S_P_SALES  CHAR(1)     NOT NULL,
     S_P_PURCHASE CHAR(1)   NOT NULL,
     S_P_ENGINEER CHAR(1)   NOT NULL,
     CONSTRAINT PK_SCECUSD PRIMARY KEY (KBID,DSINT,GRINT),
     CONSTRAINT FK_CUSD_CUHD FOREIGN KEY(KBID,DSINT) REFERENCES SCECUHD(KBID,DSINT)
)
GO

CREATE TABLE SCECUSDT (
     KBID   INT NOT NULL,
     DSINT  INT NOT NULL,
     GRINT  INT NOT NULL,
     LANGUAGEID CHAR(1) NOT NULL,
     GRTXT  NCHAR(30),
     TSTXT  NCHAR(10),
     CONSTRAINT PK_SCEUSDT PRIMARY KEY (KBID,DSINT,GRINT,LANGUAGEID),
     CONSTRAINT FK_CUSDT_CUSD FOREIGN KEY(KBID,DSINT,GRINT) REFERENCES SCECUSD(KBID,DSINT,GRINT)
)
GO

CREATE TABLE SCECUCO (
     KBID   INT  NOT NULL,
     DSINT  INT  NOT NULL,
     GRINT  INT  NOT NULL,
     CHARID INT  NOT NULL,
     COUNTER   SMALLINT NOT NULL,
     CONSTRAINT PK_SCECUCO PRIMARY KEY (KBID,DSINT,GRINT,CHARID),
     CONSTRAINT FK_CUCO_CUSD FOREIGN KEY(KBID,DSINT,GRINT) REFERENCES SCECUSD(KBID,DSINT,GRINT),
     CONSTRAINT FK_CUCO_CHARAC FOREIGN KEY(KBID,CHARID) REFERENCES SCECHARAC(KBID,CHARID),
     CONSTRAINT FK_CHARAC_KB FOREIGN KEY  (KBID) REFERENCES SCEKB (KBID)
)
GO

CREATE TABLE SCELNGTXT (
     KBID   INT  NOT NULL,
     OBJID  INT  NOT NULL,
     OBJTYPE    SMALLINT NOT NULL,
     LTXTTYPE   CHAR(4)  NOT NULL,
     LANGUAGEID CHAR(1)  NOT NULL,
     LINEID SMALLINT NOT NULL,
     TEXTFORM   CHAR(4),
     TEXTLINE   NCHAR(132),
     CONSTRAINT PK_SCELNGTXT PRIMARY KEY (KBID,OBJID,OBJTYPE,LTXTTYPE,LANGUAGEID,LINEID),
     CONSTRAINT FK_LNGTXT_KB FOREIGN KEY(KBID) REFERENCES SCEKB(KBID)
)
GO

CREATE TABLE SCEDOCKEY (
     KBID   INT  NOT NULL,
     DOCUID INT  NOT NULL,
     DOCUMENT   CHAR(25) NOT NULL,
     DOCTYPE    CHAR(3)  NOT NULL,
     DOCPART    CHAR(3)  NOT NULL,
     DOCVERS    CHAR(2)  NOT NULL,
     CONSTRAINT PK_SCEDOCKEY PRIMARY KEY (KBID,DOCUID),
     CONSTRAINT FK_DOCKEY_KB FOREIGN KEY(KBID) REFERENCES SCEKB(KBID),
     CONSTRAINT SK_SCEDOCKEY UNIQUE(DOCUMENT,DOCTYPE,DOCPART,DOCVERS)
)
GO

CREATE TABLE SCEDOCOBJ (
     KBID   INT NOT NULL,
     DOCUID INT NOT NULL,
     OBJID  INT NOT NULL,
     OBJTYPE    INT NOT NULL,
     CONSTRAINT PK_DOCOBJ PRIMARY KEY(KBID,DOCUID,OBJID,OBJTYPE),
     CONSTRAINT FK_DOCOBJ_DOCKEY FOREIGN KEY(KBID,DOCUID) REFERENCES SCEDOCKEY(KBID,DOCUID)
)
GO

CREATE TABLE SCEDRAO (
     DOCUMENT   CHAR(25)      NOT NULL,
     DOCTYPE    CHAR(3)       NOT NULL,
     DOCPART    CHAR(3)       NOT NULL,
     DOCVERS    CHAR(2)       NOT NULL,
     ORLN       INT           NOT NULL,
     ORBLK      LONGVARBINARY NOT NULL,
     CONSTRAINT PK_DRAO PRIMARY KEY(DOCUMENT,DOCTYPE,DOCPART,DOCVERS),
     CONSTRAINT FK_DRAO_DOCKEY FOREIGN KEY(DOCUMENT,DOCTYPE,DOCPART,DOCVERS) REFERENCES SCEDOCKEY(DOCUMENT,DOCTYPE,DOCPART,DOCVERS)
)
GO

CREATE TABLE SMOSCEINIT (
     MANDT      CHAR(3)      NULL,
     SFASCEINIT VARCHAR(32)  NULL,
     KBID       INT          NOT NULL,
     BUILD      INT          NOT NULL,
     SEGMNO     INT          NOT NULL,
     BLKCNT     INT          NOT NULL,
     ACTVERS    INT          NULL,
     CONSUMED   VARCHAR(1)   NULL,
     SEGMNAME   VARCHAR(30)  NOT NULL,
     BLKLEN     SMALLINT     NOT NULL,
     DATA       NVARCHAR NULL,
     TR_USER    VARCHAR(32)  NULL,
     TR_ID      VARCHAR(32)  NULL,
     TR_STATUS  VARCHAR(4)   NULL,
     DELETED    VARCHAR(1)   NULL,
     CONSTRAINT PK_SMOSCEINIT PRIMARY KEY(KBID,BUILD,SEGMNO,BLKCNT)
)
GO

CREATE TABLE SMOSCEDELT (
     MANDT      CHAR(3)      NULL,
     SFASCEDELT VARCHAR(32)  NULL,
     KBID       INT          NOT NULL,
     BUILD      INT          NOT NULL,
     SEGMNO     INT          NOT NULL,
     BLKCNT     INT          NOT NULL,
     ACTVERS    INT          NULL,
     CONSUMED   VARCHAR(1)   NULL,
     SEGMNAME   VARCHAR(30)  NOT NULL,
     BLKLEN     SMALLINT     NOT NULL,
     DATA       NVARCHAR NULL,
     TR_USER    VARCHAR(32)  NULL,
     TR_ID      VARCHAR(32)  NULL,
     TR_STATUS  VARCHAR(4)   NULL,
     DELETED    VARCHAR(1)   NULL,
     CONSTRAINT PK_SMOSCEINIT PRIMARY KEY(KBID,BUILD,SEGMNO,BLKCNT)
)
GO
