
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ss: <http://www.inmindcomputing.com/ssc/submodel.owl#>
PREFIX ps: <http://www.inmindcomputing.com/platform/platform-schema.owl#>
PREFIX as: <http://www.inmindcomputing.com/application/application-schema.owl#>
PREFIX ase: <http://www.inmindcomputing.com/application/application-schema-ext.owl#>
PREFIX sec: <http://www.inmindcomputing.com/security/security-implementation.owl#>
PREFIX wi: <http://www.inmindcomputing.com/application/workItem-implementation.owl#>
PREFIX pcs: <http://www.inmindcomputing.com/application/products/products-schema.owl#>
PREFIX pcsm: <http://www.inmindcomputing.com/application/products/products-schema-metalstamping.owl#>
PREFIX pcsp: <http://www.inmindcomputing.com/application/products/products-schema-process.owl#>
PREFIX pcst: <http://www.inmindcomputing.com/application/products/products-schema-tooling.owl#>
PREFIX pcs-mrb: <http://www.inmindcomputing.com/application/products/products-schema-mrb.owl#>
PREFIX pcs-kb: <http://www.inmindcomputing.com/application/products/products-schema-knowledgebase.owl#>
PREFIX ai: <http://www.inmindcomputing.com/application/application-implementation.owl#>
PREFIX pci: <http://www.inmindcomputing.com/application/products/products-implementation.owl#> 
 
